language: java

jdk:
  - openjdk11

stages:
  - test
  - name: release
    if: (branch =~ ^release\/.*$) AND (NOT type = pull_request)

jobs:
  include:
    - stage: test
      script:
        - ./gradlew check
    - stage: release
      script:
        - ./gradlew clean build publish
        - ./gradlew githubRelease